name    'gerardh-osrepos'
version '1.7.0'
source 'UNKNOWN'
author 'Gerard Hickey'
license 'Apache License, Version 2.0'
summary 'Maintain OS repo files'
description 'Create OS files for connecting to internal OS repo files'
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'